import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pluginsDir = path.resolve(__dirname, '../src/plugins');
const registryFile = path.resolve(__dirname, '../src/lib/auto-registry.gen.ts');
const schemaFile = path.resolve(__dirname, '../src/db/auto-schema.gen.ts');

/**
 * 插件自动化扫描引擎
 * 遍历 src/plugins，根据目录结构自动生成 Drizzle Schema 和 Hono Registry 桥接代码
 */
async function sync() {
  console.log('🔍 [Plugin Discovery] Scanning for active plugins...');
  
  if (!fs.existsSync(pluginsDir)) {
    console.error('❌ Plugins directory NOT FOUND at:', pluginsDir);
    return;
  }

  const items = fs.readdirSync(pluginsDir);
  const plugins = items.filter(item => {
    const fullPath = path.join(pluginsDir, item);
    return fs.statSync(fullPath).isDirectory() && fs.existsSync(path.join(fullPath, 'manifest.ts'));
  });

  console.log(`✨ Found ${plugins.length} plugin candidates: [${plugins.join(', ')}]`);

  // --- 1. 生成 Registry 桥接代码 ---
  let registryImports = `import { lazy } from 'react';\n`;
  let registryEntries = `export const PLUGIN_CODE_REGISTRY: Record<string, any> = {\n`;

  // 这里的 import 使用静态字符串拼接，确保 Vite 能够识别并进行 Tree Shaking 和 Bundle
  plugins.forEach(slug => {
    registryImports += `// Plugin: ${slug}\n`;
    // 约定: 插件管理端 UI 入口固定为 admin/index.tsx
    registryImports += `const ${slug}AdminUI = lazy(() => import('../plugins/${slug}/admin/index').catch(() => ({ default: () => null })));\n`;
    
    registryEntries += `  '${slug}': {\n`;
    registryEntries += `    getAdminApp: async () => (await import('../plugins/${slug}/index').catch(() => ({}))).default?.admin,\n`;
    registryEntries += `    getStorefrontApp: async () => (await import('../plugins/${slug}/index').catch(() => ({}))).default?.storefront,\n`;
    registryEntries += `    getManifest: async () => (await import('../plugins/${slug}/manifest').catch(() => ({}))).MANIFEST,\n`;
    registryEntries += `    getInit: async () => (await import('../plugins/${slug}/index').catch(() => ({}))).default?.init,\n`;
    registryEntries += `    frontend: ${slug}AdminUI,\n`;
    registryEntries += `  },\n`;
  });

  registryEntries += `};\n\n`;
  registryEntries += `/** 全局初始化代理 */\nexport const initializeAllPlugins = () => {\n  Object.keys(PLUGIN_CODE_REGISTRY).forEach(async (slug) => {\n    const init = await PLUGIN_CODE_REGISTRY[slug].getInit();\n    if (init) init();\n  });\n};\n`;

  fs.writeFileSync(registryFile, registryImports + '\n' + registryEntries);

  // --- 2. 生成 Schema 桥接代码 ---
  let schemaContent = `// [AUTO-GENERATED] DO NOT EDIT MANUALLY\n// This file is generated by scripts/sync-plugins.mjs\n\n`;
  plugins.forEach(slug => {
    const schemaPath = path.join(pluginsDir, slug, 'schema');
    if (fs.existsSync(schemaPath)) {
      const schemaFiles = fs.readdirSync(schemaPath).filter(f => f.endsWith('.ts'));
      schemaFiles.forEach(file => {
        const baseName = file.replace('.ts', '');
        schemaContent += `export * from '../plugins/${slug}/schema/${baseName}';\n`;
      });
    }
  });

  fs.writeFileSync(schemaFile, schemaContent);

  // --- 3. 生成 Middleware 桥接代码 ---
  const middlewareFile = path.resolve(__dirname, '../src/lib/auto-middleware.gen.ts');
  let middlewareContent = `// [AUTO-GENERATED] DO NOT EDIT MANUALLY\n// This file is generated by scripts/sync-plugins.mjs\n\n`;
  middlewareContent += `export const PLUGIN_MIDDLEWARES: Record<string, any> = {\n`;
  
  plugins.forEach(slug => {
    const mwPath = path.join(pluginsDir, slug, 'middleware.ts');
    if (fs.existsSync(mwPath)) {
      middlewareContent += `  '${slug}': async () => (await import('../plugins/${slug}/middleware')).default,\n`;
    }
  });
  middlewareContent += `};\n`;
  
  fs.writeFileSync(middlewareFile, middlewareContent);

  console.log('✅ [Plugin Discovery] Bridge files generated successfully.');
}

sync();
